CREATE TABLE STUDENTS(
     STUDENTID int NOT NULL AUTO_INCREMENT,
     STUDENTNAME char(50) NOT NULL,
     MAJOR char(25) NOT NULL,
     PRIMARY KEY (STUDENTID)
     );
CREATE TABLE JOBS(
     JOBID int NOT NULL AUTO_INCREMENT,
     COMPANYNAME char(50) NOT NULL,
     JOBTITLE char(50) NOT NULL,
     SALARY int NOT NULL,
     DESIREDMAJOR char(50) NOT NULL,
     PRIMARY KEY (JOBID),
     CHECK (SALARY >= 0)
     );

 CREATE TABLE APPLICATIONS(
     STUDENTID int NOT NULL,
     JOBID int NOT NULL,
     FOREIGN KEY (STUDENTID) REFERENCES STUDENTS(STUDENTID),
     FOREIGN KEY (JOBID) REFERENCES JOBS(JOBID)
     );
     
INSERT INTO STUDENTS VALUES (1, 'SPENCER SMITH','Computer Science');
INSERT INTO STUDENTS VALUES (2, 'LEVI CRIDER','Computer Science');
INSERT INTO JOBS VALUES (4, 'WALMART','IT INTERN', '45000', 'Computer Science');
INSERT INTO JOBS VALUES (5, 'TYSON','CHICKEN WHISPERER', '90000', 'Quiet Clucking');
INSERT INTO APPLICATIONS VALUES (1, 5);
INSERT INTO APPLICATIONS VALUES (2, 4);